/**
 * 太平洋房屋｜預售與新成屋聯銷平台
 * 豐富且真實的示範資料產生器 (動態對齊當前時間)
 */

import {
  User,
  Store,
  Project,
  Unit,
  ProjectAssignment,
  Customer,
  CustomerRegistration,
  CommissionVersion,
  CommissionSnapshot,
  FollowUp,
  RenewalRequest,
  Viewing,
  Transaction,
  AuditLog,
} from '../types';

// 計算相對日期的輔助函式
export function offsetDate(daysOffset: number, hoursOffset: number = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  d.setHours(d.getHours() + hoursOffset);
  return d.toISOString();
}

export function generateInitialMockData(): {
  users: User[];
  stores: Store[];
  projects: Project[];
  units: Unit[];
  projectAssignments: ProjectAssignment[];
  customers: Customer[];
  customerRegistrations: CustomerRegistration[];
  commissionVersions: CommissionVersion[];
  commissionSnapshots: CommissionSnapshot[];
  followUps: FollowUp[];
  renewalRequests: RenewalRequest[];
  viewings: Viewing[];
  transactions: Transaction[];
  auditLogs: AuditLog[];
} {
  // 1. 示範帳號 (5位)
  const users: User[] = [
    {
      id: 'usr_center_admin',
      username: 'center_admin',
      name: '王中心',
      role: 'center_admin',
      title: '代銷中心 營運協理',
      phone: '02-8772-9988 #801',
      email: 'center.admin@pacific-realty.demo',
    },
    {
      id: 'usr_store_mgr_a',
      username: 'store_mgr_a',
      name: '陳店長',
      role: 'store_manager',
      storeId: 'store_daan_a',
      storeName: '示範A店（大安旗艦店）',
      title: '大安旗艦店 店長',
      phone: '02-2708-1122',
      email: 'daan.mgr@pacific-realty.demo',
    },
    {
      id: 'usr_agent_a',
      username: 'agent_a',
      name: '林業務',
      role: 'agent',
      storeId: 'store_daan_a',
      storeName: '示範A店（大安旗艦店）',
      title: '大安旗艦店 資深置產顧問',
      phone: '0988-123-456',
      email: 'lin.agent@pacific-realty.demo',
    },
    {
      id: 'usr_store_mgr_b',
      username: 'store_mgr_b',
      name: '張店長',
      role: 'store_manager',
      storeId: 'store_xinyi_b',
      storeName: '示範B店（信義加盟店）',
      title: '信義加盟店 店長',
      phone: '02-8789-3355',
      email: 'xinyi.mgr@pacific-realty.demo',
    },
    {
      id: 'usr_agent_b',
      username: 'agent_b',
      name: '黃業務',
      role: 'agent',
      storeId: 'store_xinyi_b',
      storeName: '示範B店（信義加盟店）',
      title: '信義加盟店 置產專員',
      phone: '0977-654-321',
      email: 'huang.agent@pacific-realty.demo',
    },
  ];

  // 2. 門店 (2家門店)
  const stores: Store[] = [
    {
      id: 'store_daan_a',
      name: '示範A店（大安旗艦店）',
      code: 'DAAN-01',
      address: '台北市大安區復興南路一段 188 號',
      phone: '02-2708-1122',
      managerName: '陳店長',
      status: 'ACTIVE',
      createdAt: offsetDate(-90),
      updatedAt: offsetDate(-90),
    },
    {
      id: 'store_xinyi_b',
      name: '示範B店（信義加盟店）',
      code: 'XINYI-02',
      address: '台北市信義區忠孝東路五段 236 號',
      phone: '02-8789-3355',
      managerName: '張店長',
      status: 'ACTIVE',
      createdAt: offsetDate(-90),
      updatedAt: offsetDate(-90),
    },
  ];

  // 3. 建案 (3案：預售屋、新成屋、餘屋)
  const projects: Project[] = [
    {
      id: 'proj_dunnan',
      name: '太平洋敦南峰景',
      developer: '太平洋建設股份有限公司',
      productType: 'PRE_SALE',
      city: '台北市',
      district: '大安區',
      address: '敦化南路二段 210 號旁',
      receptionContact: '02-2735-8899（接待中心 李專案）',
      description: '大安敦南林蔭首席，四面臨路稀有角地，雙制震鋼骨地標宅，戶戶邊間採光佳。',
      highlights: ['敦化南路正林蔭大道', 'SC鋼骨+住友制震', '戶戶挑高3米6', '鄰近信義安和捷運站'],
      totalUnits: 48,
      availableUnits: 12,
      status: 'ON_SALE',
      attachmentUrls: ['https://example.com/docs/dunnan_floorplan.pdf'],
      currentCommissionVersionId: 'comm_dunnan_v2',
      createdAt: offsetDate(-60),
      updatedAt: offsetDate(-10),
    },
    {
      id: 'proj_park_shoufu',
      name: '太平洋公園首馥',
      developer: '太極置地開發',
      productType: 'NEW_CONSTRUCTION',
      city: '台北市',
      district: '信義區',
      address: '松德路 168 巷 22 號',
      receptionContact: '02-8780-6677（現場銷售 謝經理）',
      description: '信義計畫區旁純住靜巷新成屋，正面萬坪象山綠意，全新完工即可入主。',
      highlights: ['全新成屋即刻入住', '中鼎工程營造保證', '戶戶配大平面車位', '綠建築黃金級認證'],
      totalUnits: 36,
      availableUnits: 8,
      status: 'ON_SALE',
      attachmentUrls: ['https://example.com/docs/park_shoufu_catalog.pdf'],
      currentCommissionVersionId: 'comm_park_v1',
      createdAt: offsetDate(-50),
      updatedAt: offsetDate(-50),
    },
    {
      id: 'proj_mori_villa',
      name: '太平洋森活美墅',
      developer: '太設景觀開發',
      productType: 'SURPLUS_HOUSE',
      city: '台北市',
      district: '文山區',
      address: '政大一街 88 號',
      receptionContact: '02-2938-1122（政大接待所 高副理）',
      description: '政大附中優質文教特區，最後6席限量精工花園電梯別墅，永久綠意視野。',
      highlights: ['政大文教生活圈', '私家庭院與獨立車庫', '電梯別墅三代同堂', '現況餘屋超值讓利'],
      totalUnits: 24,
      availableUnits: 6,
      status: 'ON_SALE',
      attachmentUrls: ['https://example.com/docs/mori_villa_spec.pdf'],
      currentCommissionVersionId: 'comm_mori_v1',
      createdAt: offsetDate(-75),
      updatedAt: offsetDate(-75),
    },
  ];

  // 4. 建案指派 (符合規則：敦南A+B店、公園首馥僅A店、森活美墅僅B店)
  const projectAssignments: ProjectAssignment[] = [
    {
      id: 'asg_dunnan_a',
      projectId: 'proj_dunnan',
      storeId: 'store_daan_a',
      assignedAt: offsetDate(-60),
      assignedBy: '王中心',
      status: 'ACTIVE',
      changeReason: '大安區主力建案指派在地旗艦店聯合銷售',
    },
    {
      id: 'asg_dunnan_b',
      projectId: 'proj_dunnan',
      storeId: 'store_xinyi_b',
      assignedAt: offsetDate(-60),
      assignedBy: '王中心',
      status: 'ACTIVE',
      changeReason: '信義店客源具地緣跨區置產需求，共同指派銷售',
    },
    {
      id: 'asg_park_a',
      projectId: 'proj_park_shoufu',
      storeId: 'store_daan_a',
      assignedAt: offsetDate(-50),
      assignedBy: '王中心',
      status: 'ACTIVE',
      changeReason: '大安旗艦店獨家承接銷售',
    },
    {
      id: 'asg_mori_b',
      projectId: 'proj_mori_villa',
      storeId: 'store_xinyi_b',
      assignedAt: offsetDate(-75),
      assignedBy: '王中心',
      status: 'ACTIVE',
      changeReason: '信義加盟店專案團隊承接銷售',
    },
  ];

  // 5. 分佣版本 (展示版本演進，舊客戶鎖定 V1.0，新客戶鎖定 V2.0)
  const commissionVersions: CommissionVersion[] = [
    {
      id: 'comm_dunnan_v1',
      projectId: 'proj_dunnan',
      versionNumber: 'V1.0',
      effectiveDate: offsetDate(-60),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 3.0,
      centerPercentage: 30,
      storePercentage: 70,
      note: '建案開案初期聯銷分佣辦法 (總價 3.0%)',
      publishedBy: '王中心',
      createdAt: offsetDate(-60),
    },
    {
      id: 'comm_dunnan_v2',
      projectId: 'proj_dunnan',
      versionNumber: 'V2.0',
      effectiveDate: offsetDate(-15),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 3.5, // 總佣金調高至 3.5%
      centerPercentage: 25,
      storePercentage: 75,
      note: '中秋強銷加碼專案，門店分佣提升至 75%，總分佣提升至 3.5%',
      publishedBy: '王中心',
      createdAt: offsetDate(-15),
    },
    {
      id: 'comm_park_v1',
      projectId: 'proj_park_shoufu',
      versionNumber: 'V1.0',
      effectiveDate: offsetDate(-50),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 2.8,
      centerPercentage: 30,
      storePercentage: 70,
      note: '公園首馥成屋常態聯銷專案 (總價 2.8%)',
      publishedBy: '王中心',
      createdAt: offsetDate(-50),
    },
    {
      id: 'comm_mori_v1',
      projectId: 'proj_mori_villa',
      versionNumber: 'V1.0',
      effectiveDate: offsetDate(-75),
      formulaType: 'FIXED_AMOUNT',
      fixedAmount: 800000, // 固定每戶 80 萬獎金
      centerPercentage: 20,
      storePercentage: 80,
      note: '別墅餘屋去化特惠方案：每戶成交固定總獎勵 80 萬元 (門店得 64 萬)',
      publishedBy: '王中心',
      createdAt: offsetDate(-75),
    },
  ];

  // 6. 戶別 (每案至少 6 戶，包含底價，底價僅中心可見)
  const units: Unit[] = [
    // 敦南峰景 (8戶)
    {
      id: 'unit_dn_a1_12f',
      projectId: 'proj_dunnan',
      building: 'A棟',
      unitNumber: 'A1-12F',
      floor: 12,
      pattern: '3房2廳2衛',
      areaPings: 46.8,
      parkingInfo: 'B2 坡道平面 14 號',
      listPrice: 42800000,
      bottomPrice: 38500000,
      status: 'RESERVED_DEPOSIT', // 已有下訂申報
      createdAt: offsetDate(-60),
      updatedAt: offsetDate(-2),
    },
    {
      id: 'unit_dn_a2_8f',
      projectId: 'proj_dunnan',
      building: 'A棟',
      unitNumber: 'A2-8F',
      floor: 8,
      pattern: '4房2廳3衛',
      areaPings: 58.5,
      parkingInfo: 'B2 坡道平面 18 號',
      listPrice: 53800000,
      bottomPrice: 48000000,
      status: 'SIGNED', // 已簽約
      createdAt: offsetDate(-60),
      updatedAt: offsetDate(-5),
    },
    {
      id: 'unit_dn_a3_5f',
      projectId: 'proj_dunnan',
      building: 'A棟',
      unitNumber: 'A3-5F',
      floor: 5,
      pattern: '2房2廳1衛',
      areaPings: 28.6,
      parkingInfo: 'B3 機械車位 05 號',
      listPrice: 26800000,
      bottomPrice: 24000000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-60),
      updatedAt: offsetDate(-60),
    },
    {
      id: 'unit_dn_b1_9f',
      projectId: 'proj_dunnan',
      building: 'B棟',
      unitNumber: 'B1-9F',
      floor: 9,
      pattern: '3房2廳2衛',
      areaPings: 45.2,
      parkingInfo: 'B2 坡道平面 22 號',
      listPrice: 41500000,
      bottomPrice: 37000000,
      status: 'NEGOTIATING',
      createdAt: offsetDate(-60),
      updatedAt: offsetDate(-3),
    },
    {
      id: 'unit_dn_b2_11f',
      projectId: 'proj_dunnan',
      building: 'B棟',
      unitNumber: 'B2-11F',
      floor: 11,
      pattern: '3房2廳2衛',
      areaPings: 47.1,
      parkingInfo: 'B2 坡道平面 25 號',
      listPrice: 43200000,
      bottomPrice: 38800000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-60),
      updatedAt: offsetDate(-60),
    },
    {
      id: 'unit_dn_b3_3f',
      projectId: 'proj_dunnan',
      building: 'B棟',
      unitNumber: 'B3-3F',
      floor: 3,
      pattern: '2房2廳1衛',
      areaPings: 29.3,
      parkingInfo: 'B3 坡道平面 08 號',
      listPrice: 25900000,
      bottomPrice: 23200000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-60),
      updatedAt: offsetDate(-60),
    },
    {
      id: 'unit_dn_a1_15f',
      projectId: 'proj_dunnan',
      building: 'A棟',
      unitNumber: 'A1-15F（頂樓景觀戶）',
      floor: 15,
      pattern: '4房2廳3衛',
      areaPings: 62.4,
      parkingInfo: 'B1 雙平面車位 01/02',
      listPrice: 66800000,
      bottomPrice: 59800000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-60),
      updatedAt: offsetDate(-60),
    },

    // 公園首馥 (6戶)
    {
      id: 'unit_ps_101',
      projectId: 'proj_park_shoufu',
      building: '景觀棟',
      unitNumber: '10F-A',
      floor: 10,
      pattern: '3房2廳2衛',
      areaPings: 52.8,
      parkingInfo: 'B1 平面車位 11 號',
      listPrice: 49800000,
      bottomPrice: 45000000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-50),
      updatedAt: offsetDate(-50),
    },
    {
      id: 'unit_ps_102',
      projectId: 'proj_park_shoufu',
      building: '景觀棟',
      unitNumber: '7F-A',
      floor: 7,
      pattern: '3房2廳2衛',
      areaPings: 52.8,
      parkingInfo: 'B1 平面車位 15 號',
      listPrice: 47500000,
      bottomPrice: 42800000,
      status: 'NEGOTIATING',
      createdAt: offsetDate(-50),
      updatedAt: offsetDate(-4),
    },
    {
      id: 'unit_ps_103',
      projectId: 'proj_park_shoufu',
      building: '景觀棟',
      unitNumber: '5F-B',
      floor: 5,
      pattern: '2房2廳2衛',
      areaPings: 35.6,
      parkingInfo: 'B2 平面車位 03 號',
      listPrice: 33800000,
      bottomPrice: 30500000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-50),
      updatedAt: offsetDate(-50),
    },
    {
      id: 'unit_ps_104',
      projectId: 'proj_park_shoufu',
      building: '景觀棟',
      unitNumber: '3F-B',
      floor: 3,
      pattern: '2房2廳2衛',
      areaPings: 35.6,
      parkingInfo: 'B2 平面車位 06 號',
      listPrice: 32000000,
      bottomPrice: 28900000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-50),
      updatedAt: offsetDate(-50),
    },
    {
      id: 'unit_ps_105',
      projectId: 'proj_park_shoufu',
      building: '景觀棟',
      unitNumber: '11F-露台特戶',
      floor: 11,
      pattern: '4房2廳3衛',
      areaPings: 68.2,
      parkingInfo: 'B1 雙平面車位 08/09',
      listPrice: 68000000,
      bottomPrice: 61500000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-50),
      updatedAt: offsetDate(-50),
    },
    {
      id: 'unit_ps_106',
      projectId: 'proj_park_shoufu',
      building: '景觀棟',
      unitNumber: '2F-花園戶',
      floor: 2,
      pattern: '3房2廳2衛',
      areaPings: 51.5,
      parkingInfo: 'B2 平面車位 19 號',
      listPrice: 44500000,
      bottomPrice: 40200000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-50),
      updatedAt: offsetDate(-50),
    },

    // 森活美墅 (6戶)
    {
      id: 'unit_mv_v1',
      projectId: 'proj_mori_villa',
      building: 'A區',
      unitNumber: 'A1 棟尊榮別墅',
      floor: 4,
      pattern: '5房3廳5衛 (電梯別墅)',
      areaPings: 92.5,
      parkingInfo: '私家室內庭院雙車位',
      listPrice: 58800000,
      bottomPrice: 52000000,
      status: 'DEAL_CLOSED', // 已成交
      createdAt: offsetDate(-75),
      updatedAt: offsetDate(-10),
    },
    {
      id: 'unit_mv_v2',
      projectId: 'proj_mori_villa',
      building: 'A區',
      unitNumber: 'A2 棟花園別墅',
      floor: 4,
      pattern: '4房3廳4衛 (電梯別墅)',
      areaPings: 86.2,
      parkingInfo: '私家庭院獨立車庫',
      listPrice: 53500000,
      bottomPrice: 47800000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-75),
      updatedAt: offsetDate(-75),
    },
    {
      id: 'unit_mv_v3',
      projectId: 'proj_mori_villa',
      building: 'B區',
      unitNumber: 'B1 棟景觀別墅',
      floor: 4,
      pattern: '4房3廳4衛 (電梯別墅)',
      areaPings: 84.8,
      parkingInfo: '私家庭院獨立車庫',
      listPrice: 51800000,
      bottomPrice: 46000000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-75),
      updatedAt: offsetDate(-75),
    },
    {
      id: 'unit_mv_v4',
      projectId: 'proj_mori_villa',
      building: 'B區',
      unitNumber: 'B2 棟景觀別墅',
      floor: 4,
      pattern: '4房3廳4衛 (電梯別墅)',
      areaPings: 84.8,
      parkingInfo: '私家庭院獨立車庫',
      listPrice: 51800000,
      bottomPrice: 46000000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-75),
      updatedAt: offsetDate(-75),
    },
    {
      id: 'unit_mv_v5',
      projectId: 'proj_mori_villa',
      building: 'C區',
      unitNumber: 'C1 棟邊間旗艦',
      floor: 4,
      pattern: '5房3廳5衛 (電梯別墅)',
      areaPings: 96.0,
      parkingInfo: '私家庭院三車位',
      listPrice: 62500000,
      bottomPrice: 55000000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-75),
      updatedAt: offsetDate(-75),
    },
    {
      id: 'unit_mv_v6',
      projectId: 'proj_mori_villa',
      building: 'C區',
      unitNumber: 'C2 棟靜音別墅',
      floor: 4,
      pattern: '4房3廳4衛 (電梯別墅)',
      areaPings: 88.3,
      parkingInfo: '私家庭院獨立車庫',
      listPrice: 54800000,
      bottomPrice: 48500000,
      status: 'AVAILABLE',
      createdAt: offsetDate(-75),
      updatedAt: offsetDate(-75),
    },
  ];

  // 7. 虛構客戶 (12位)
  const customers: Customer[] = [
    {
      id: 'cust_01',
      name: '李先生（示範客戶）',
      phone: '0912-345-678', // 此客戶同案重複登記於 A店 與 B店，供判定測試
      email: 'demo_lee@example.com',
      source: '網路廣告預約',
      requirementNote: '需大三房採光好，有換屋需求，預算 4000~4500 萬。',
      budgetMin: 4000,
      budgetMax: 4500,
      createdAt: offsetDate(-25),
    },
    {
      id: 'cust_02',
      name: '張董事長（示範客戶）',
      phone: '0922-888-999',
      email: 'demo_chang@example.com',
      source: '門店在地VIP熟客',
      requirementNote: '企業資產配置，欲購入高樓層景觀大戶，預算充足。',
      budgetMin: 5000,
      budgetMax: 7000,
      createdAt: offsetDate(-26),
    },
    {
      id: 'cust_03',
      name: '林醫師（示範客戶）',
      phone: '0933-777-666',
      email: 'demo_lin@example.com',
      source: '案場自來客轉介',
      requirementNote: '偏好大安區靜巷成屋，重視隔音與生活機能。',
      budgetMin: 3500,
      budgetMax: 4800,
      createdAt: offsetDate(-35),
    },
    {
      id: 'cust_04',
      name: '趙建築師（示範客戶）',
      phone: '0955-111-222',
      email: 'demo_chao@example.com',
      source: '太平洋官方LINE@諮詢',
      requirementNote: '重視建築結構與制震規劃，考慮投資自住兼顧。',
      budgetMin: 3800,
      budgetMax: 4500,
      createdAt: offsetDate(-24),
    },
    {
      id: 'cust_05',
      name: '孫總經理（示範客戶）',
      phone: '0966-333-444',
      email: 'demo_sun@example.com',
      source: '信義店在地經營拜訪',
      requirementNote: '尋找文山區或信義區景觀豪邸，三代同堂家庭。',
      budgetMin: 5000,
      budgetMax: 6500,
      createdAt: offsetDate(-28),
    },
    {
      id: 'cust_06',
      name: '高會計師（示範客戶）',
      phone: '0977-222-111',
      email: 'demo_kao@example.com',
      source: '親友轉介',
      requirementNote: '首購兩房置產，希望近捷運、公設比合理。',
      budgetMin: 2400,
      budgetMax: 2800,
      createdAt: offsetDate(-27),
    },
    {
      id: 'cust_07',
      name: '吳教授（示範客戶）',
      phone: '0988-555-444',
      email: 'demo_wu@example.com',
      source: '政大校園地緣客',
      requirementNote: '為退休準備，喜愛文教區安靜環境與獨立花園。',
      budgetMin: 5000,
      budgetMax: 6000,
      createdAt: offsetDate(-30),
    },
    {
      id: 'cust_08',
      name: '許設計師（示範客戶）',
      phone: '0919-666-888',
      email: 'demo_hsu@example.com',
      source: 'FB專頁廣告留言',
      requirementNote: '工作室與住家複合使用，偏好採光天井與大面寬。',
      budgetMin: 4200,
      budgetMax: 5000,
      createdAt: offsetDate(-20),
    },
    {
      id: 'cust_09',
      name: '鄭協理（示範客戶）',
      phone: '0928-123-987',
      email: 'demo_cheng@example.com',
      source: '大安門店自來客',
      requirementNote: '兒子結婚新成屋成家，需 3 房規劃。',
      budgetMin: 4500,
      budgetMax: 5200,
      createdAt: offsetDate(-18),
    },
    {
      id: 'cust_10',
      name: '方總監（示範客戶）',
      phone: '0937-456-789',
      email: 'demo_fang@example.com',
      source: '信義加盟店推薦',
      requirementNote: '喜愛象山綠意，預計一個月內完成簽約下訂。',
      budgetMin: 3200,
      budgetMax: 3800,
      createdAt: offsetDate(-15),
    },
    {
      id: 'cust_11',
      name: '何院長（示範客戶）',
      phone: '0958-333-888',
      email: 'demo_ho@example.com',
      source: '電訪名單開發',
      requirementNote: '希望看文山區獨棟別墅，需有輪椅無障礙電梯。',
      budgetMin: 5500,
      budgetMax: 6500,
      createdAt: offsetDate(-40),
    },
    {
      id: 'cust_12',
      name: '蔡副總（示範客戶）',
      phone: '0981-999-000',
      email: 'demo_tsai@example.com',
      source: '總公司聯合展銷派單',
      requirementNote: '敦南峰景 V2.0 加碼新案客戶，鎖定頂樓景觀戶。',
      budgetMin: 6000,
      budgetMax: 7000,
      createdAt: offsetDate(-5),
    },
  ];

  // 8. 客戶建案登記 (核心測試案例矩陣)
  const customerRegistrations: CustomerRegistration[] = [
    // 案例 1：A店 林業務 - 敦南峰景 (一般正常保留，剩餘 22 天，鎖定 V1.0 快照)
    {
      id: 'reg_dn_01_a',
      customerId: 'cust_01',
      projectId: 'proj_dunnan',
      intendedUnitId: 'unit_dn_a1_12f',
      storeId: 'store_daan_a',
      agentId: 'usr_agent_a',
      status: 'ACTIVE',
      reservationStartDate: offsetDate(-8),
      reservationExpiryDate: offsetDate(22), // 剩餘 22 天
      notes: '首次洽談敦南峰景 A1-12F，已給平面圖與開價。',
      commissionSnapshotId: 'snap_reg_01',
      createdAt: offsetDate(-8),
      updatedAt: offsetDate(-8),
    },
    // 案例 2：B店 黃業務 - 敦南峰景 (重複登記同一位客戶 李先生 0912-345-678，觸發歸屬待判定)
    {
      id: 'reg_dn_01_b_conflict',
      customerId: 'cust_01',
      projectId: 'proj_dunnan',
      intendedUnitId: 'unit_dn_b1_9f',
      storeId: 'store_xinyi_b',
      agentId: 'usr_agent_b',
      status: 'CONFLICT_PENDING', // 歸屬待判定
      reservationStartDate: offsetDate(-2),
      reservationExpiryDate: offsetDate(28),
      notes: '信義店業務嘗試登記相同李先生，系統偵測同案已有 A店 有效保留，進入代銷中心判定程序。',
      commissionSnapshotId: 'snap_reg_conflict_01',
      conflictOriginalRegId: 'reg_dn_01_a',
      createdAt: offsetDate(-2),
      updatedAt: offsetDate(-2),
    },
    // 案例 3：A店 林業務 - 敦南峰景 (7天內即將到期：剩餘 4 天，有有效追蹤，可申請續期)
    {
      id: 'reg_dn_02_expiring_eligible',
      customerId: 'cust_02',
      projectId: 'proj_dunnan',
      intendedUnitId: 'unit_dn_a2_8f',
      storeId: 'store_daan_a',
      agentId: 'usr_agent_a',
      status: 'EXPIRING_SOON',
      reservationStartDate: offsetDate(-26),
      reservationExpiryDate: offsetDate(4), // 剩餘 4 天
      notes: '張董已參觀接待中心，近期需申請續期保留。',
      commissionSnapshotId: 'snap_reg_02',
      createdAt: offsetDate(-26),
      updatedAt: offsetDate(-2),
    },
    // 案例 4：A店 陳店長 - 公園首馥 (已到期：到期 3 天前，保留歷史不刪除)
    {
      id: 'reg_ps_03_expired',
      customerId: 'cust_03',
      projectId: 'proj_park_shoufu',
      intendedUnitId: 'unit_ps_102',
      storeId: 'store_daan_a',
      agentId: 'usr_store_mgr_a',
      status: 'EXPIRED',
      reservationStartDate: offsetDate(-33),
      reservationExpiryDate: offsetDate(-3), // 到期 3 天前
      notes: '林醫師保留期已過，暫未補足續期要件，留存歷史紀錄待重啟。',
      commissionSnapshotId: 'snap_reg_03',
      createdAt: offsetDate(-33),
      updatedAt: offsetDate(-3),
    },
    // 案例 5：B店 黃業務 - 敦南峰景 (7天內即將到期：剩餘 3 天，但「無有效追蹤」，申請續期時應被系統阻擋)
    {
      id: 'reg_dn_04_ineligible',
      customerId: 'cust_04',
      projectId: 'proj_dunnan',
      intendedUnitId: 'unit_dn_b2_11f',
      storeId: 'store_xinyi_b',
      agentId: 'usr_agent_b',
      status: 'EXPIRING_SOON',
      reservationStartDate: offsetDate(-27),
      reservationExpiryDate: offsetDate(3), // 剩餘 3 天
      notes: '趙建築師僅有舊紀錄，14天內未有實質客戶回饋追蹤，驗證不可續期。',
      commissionSnapshotId: 'snap_reg_04',
      createdAt: offsetDate(-27),
      updatedAt: offsetDate(-27),
    },
    // 案例 6：B店 黃業務 - 森活美墅 (已送出續期申請，待代銷中心審核中)
    {
      id: 'reg_mv_05_pending_renewal',
      customerId: 'cust_05',
      projectId: 'proj_mori_villa',
      intendedUnitId: 'unit_mv_v2',
      storeId: 'store_xinyi_b',
      agentId: 'usr_agent_b',
      status: 'EXPIRING_SOON',
      reservationStartDate: offsetDate(-28),
      reservationExpiryDate: offsetDate(2), // 剩餘 2 天
      notes: '孫總帶看後極具意願，已附上帶看紀錄申請延長保留30天。',
      commissionSnapshotId: 'snap_reg_05',
      createdAt: offsetDate(-28),
      updatedAt: offsetDate(-1),
    },
    // 案例 7：A店 林業務 - 敦南峰景 (下訂申報中：已申報下訂 A1-12F，待代銷中心確認生效)
    {
      id: 'reg_dn_06_deposit_rep',
      customerId: 'cust_06',
      projectId: 'proj_dunnan',
      intendedUnitId: 'unit_dn_a1_12f',
      storeId: 'store_daan_a',
      agentId: 'usr_agent_a',
      status: 'ACTIVE',
      reservationStartDate: offsetDate(-14),
      reservationExpiryDate: offsetDate(16),
      notes: '已收小訂 10 萬元，提出下訂申報。',
      commissionSnapshotId: 'snap_reg_06',
      createdAt: offsetDate(-14),
      updatedAt: offsetDate(-1),
    },
    // 案例 8：A店 陳店長 - 敦南峰景 (已簽約：A2-8F 成交 4,880 萬，分佣快照鎖定 V1.0 3%)
    {
      id: 'reg_dn_07_signed',
      customerId: 'cust_07',
      projectId: 'proj_dunnan',
      intendedUnitId: 'unit_dn_a2_8f',
      storeId: 'store_daan_a',
      agentId: 'usr_store_mgr_a',
      status: 'CONVERTED',
      reservationStartDate: offsetDate(-45),
      reservationExpiryDate: offsetDate(-15),
      notes: '雙方已於太平洋敦南案場完成正式簽約，進入工程款繳納階段。',
      commissionSnapshotId: 'snap_reg_07',
      createdAt: offsetDate(-45),
      updatedAt: offsetDate(-10),
    },
    // 案例 9：B店 張店長 - 森活美墅 (已成交結案：A1棟別墅成交 5,300 萬，固定 80 萬佣金已結算)
    {
      id: 'reg_mv_08_deal_closed',
      customerId: 'cust_08',
      projectId: 'proj_mori_villa',
      intendedUnitId: 'unit_mv_v1',
      storeId: 'store_xinyi_b',
      agentId: 'usr_store_mgr_b',
      status: 'CONVERTED',
      reservationStartDate: offsetDate(-55),
      reservationExpiryDate: offsetDate(-25),
      notes: '已完成產權移轉過戶與交屋，佣金正式結算。',
      commissionSnapshotId: 'snap_reg_08',
      createdAt: offsetDate(-55),
      updatedAt: offsetDate(-5),
    },
    // 案例 10：A店 林業務 - 公園首馥 (僅 A 店指派建案，B 店不可見)
    {
      id: 'reg_ps_09_daan_only',
      customerId: 'cust_09',
      projectId: 'proj_park_shoufu',
      intendedUnitId: 'unit_ps_101',
      storeId: 'store_daan_a',
      agentId: 'usr_agent_a',
      status: 'ACTIVE',
      reservationStartDate: offsetDate(-10),
      reservationExpiryDate: offsetDate(20),
      notes: '鄭協理預約成屋帶看，僅大安店負責此案。',
      commissionSnapshotId: 'snap_reg_09',
      createdAt: offsetDate(-10),
      updatedAt: offsetDate(-10),
    },
    // 案例 11：B店 黃業務 - 森活美墅 (僅 B 店指派建案，A 店不可見)
    {
      id: 'reg_mv_10_xinyi_only',
      customerId: 'cust_10',
      projectId: 'proj_mori_villa',
      intendedUnitId: 'unit_mv_v3',
      storeId: 'store_xinyi_b',
      agentId: 'usr_agent_b',
      status: 'ACTIVE',
      reservationStartDate: offsetDate(-12),
      reservationExpiryDate: offsetDate(18),
      notes: '方總監看政大別墅，信義店專任銷售。',
      commissionSnapshotId: 'snap_reg_10',
      createdAt: offsetDate(-12),
      updatedAt: offsetDate(-12),
    },
    // 案例 12：A店 林業務 - 敦南峰景 (新版本 V2.0 成立後的客戶，鎖定 V2.0 3.5% 快照，與案例 1 的 V1.0 對比)
    {
      id: 'reg_dn_11_v2_snap',
      customerId: 'cust_12',
      projectId: 'proj_dunnan',
      intendedUnitId: 'unit_dn_a1_15f',
      storeId: 'store_daan_a',
      agentId: 'usr_agent_a',
      status: 'ACTIVE',
      reservationStartDate: offsetDate(-4),
      reservationExpiryDate: offsetDate(26),
      notes: '於 V2.0 強銷方案發布後登記，快照自動鎖定最新 3.5% 分佣條件。',
      commissionSnapshotId: 'snap_reg_11_v2',
      createdAt: offsetDate(-4),
      updatedAt: offsetDate(-4),
    },
  ];

  // 9. 分佣快照 (不可覆寫，記錄當時鎖定之完整條件)
  const commissionSnapshots: CommissionSnapshot[] = [
    {
      id: 'snap_reg_01',
      customerRegistrationId: 'reg_dn_01_a',
      projectId: 'proj_dunnan',
      versionId: 'comm_dunnan_v1',
      versionNumber: 'V1.0',
      lockedAt: offsetDate(-8),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 3.0,
      centerPercentage: 30,
      storePercentage: 70,
      basisDescription: '總價 3.0% 獎勵 (中心 30% / 門店 70%) - 登記時鎖定',
    },
    {
      id: 'snap_reg_conflict_01',
      customerRegistrationId: 'reg_dn_01_b_conflict',
      projectId: 'proj_dunnan',
      versionId: 'comm_dunnan_v2',
      versionNumber: 'V2.0',
      lockedAt: offsetDate(-2),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 3.5,
      centerPercentage: 25,
      storePercentage: 75,
      basisDescription: '總價 3.5% 獎勵 (中心 25% / 門店 75%) - 送件判定時鎖定',
    },
    {
      id: 'snap_reg_02',
      customerRegistrationId: 'reg_dn_02_expiring_eligible',
      projectId: 'proj_dunnan',
      versionId: 'comm_dunnan_v1',
      versionNumber: 'V1.0',
      lockedAt: offsetDate(-26),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 3.0,
      centerPercentage: 30,
      storePercentage: 70,
      basisDescription: '總價 3.0% 獎勵 (中心 30% / 門店 70%) - 登記時鎖定',
    },
    {
      id: 'snap_reg_03',
      customerRegistrationId: 'reg_ps_03_expired',
      projectId: 'proj_park_shoufu',
      versionId: 'comm_park_v1',
      versionNumber: 'V1.0',
      lockedAt: offsetDate(-33),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 2.8,
      centerPercentage: 30,
      storePercentage: 70,
      basisDescription: '總價 2.8% 獎勵 (中心 30% / 門店 70%) - 登記時鎖定',
    },
    {
      id: 'snap_reg_04',
      customerRegistrationId: 'reg_dn_04_ineligible',
      projectId: 'proj_dunnan',
      versionId: 'comm_dunnan_v1',
      versionNumber: 'V1.0',
      lockedAt: offsetDate(-27),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 3.0,
      centerPercentage: 30,
      storePercentage: 70,
      basisDescription: '總價 3.0% 獎勵 (中心 30% / 門店 70%) - 登記時鎖定',
    },
    {
      id: 'snap_reg_05',
      customerRegistrationId: 'reg_mv_05_pending_renewal',
      projectId: 'proj_mori_villa',
      versionId: 'comm_mori_v1',
      versionNumber: 'V1.0',
      lockedAt: offsetDate(-28),
      formulaType: 'FIXED_AMOUNT',
      fixedAmount: 800000,
      centerPercentage: 20,
      storePercentage: 80,
      basisDescription: '固定每戶 NT$ 800,000 元 (中心 20% / 門店 80%) - 登記時鎖定',
    },
    {
      id: 'snap_reg_06',
      customerRegistrationId: 'reg_dn_06_deposit_rep',
      projectId: 'proj_dunnan',
      versionId: 'comm_dunnan_v1',
      versionNumber: 'V1.0',
      lockedAt: offsetDate(-14),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 3.0,
      centerPercentage: 30,
      storePercentage: 70,
      basisDescription: '總價 3.0% 獎勵 (中心 30% / 門店 70%) - 登記時鎖定',
    },
    {
      id: 'snap_reg_07',
      customerRegistrationId: 'reg_dn_07_signed',
      projectId: 'proj_dunnan',
      versionId: 'comm_dunnan_v1',
      versionNumber: 'V1.0',
      lockedAt: offsetDate(-45),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 3.0,
      centerPercentage: 30,
      storePercentage: 70,
      basisDescription: '總價 3.0% 獎勵 (中心 30% / 門店 70%) - 登記時鎖定',
    },
    {
      id: 'snap_reg_08',
      customerRegistrationId: 'reg_mv_08_deal_closed',
      projectId: 'proj_mori_villa',
      versionId: 'comm_mori_v1',
      versionNumber: 'V1.0',
      lockedAt: offsetDate(-55),
      formulaType: 'FIXED_AMOUNT',
      fixedAmount: 800000,
      centerPercentage: 20,
      storePercentage: 80,
      basisDescription: '固定每戶 NT$ 800,000 元 (中心 20% / 門店 80%) - 登記時鎖定',
    },
    {
      id: 'snap_reg_09',
      customerRegistrationId: 'reg_ps_09_daan_only',
      projectId: 'proj_park_shoufu',
      versionId: 'comm_park_v1',
      versionNumber: 'V1.0',
      lockedAt: offsetDate(-10),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 2.8,
      centerPercentage: 30,
      storePercentage: 70,
      basisDescription: '總價 2.8% 獎勵 (中心 30% / 門店 70%) - 登記時鎖定',
    },
    {
      id: 'snap_reg_10',
      customerRegistrationId: 'reg_mv_10_xinyi_only',
      projectId: 'proj_mori_villa',
      versionId: 'comm_mori_v1',
      versionNumber: 'V1.0',
      lockedAt: offsetDate(-12),
      formulaType: 'FIXED_AMOUNT',
      fixedAmount: 800000,
      centerPercentage: 20,
      storePercentage: 80,
      basisDescription: '固定每戶 NT$ 800,000 元 (中心 20% / 門店 80%) - 登記時鎖定',
    },
    {
      id: 'snap_reg_11_v2',
      customerRegistrationId: 'reg_dn_11_v2_snap',
      projectId: 'proj_dunnan',
      versionId: 'comm_dunnan_v2',
      versionNumber: 'V2.0',
      lockedAt: offsetDate(-4),
      formulaType: 'PERCENTAGE_TOTAL',
      percentage: 3.5,
      centerPercentage: 25,
      storePercentage: 75,
      basisDescription: '總價 3.5% 獎勵 (中心 25% / 門店 75%) - 登記時鎖定',
    },
  ];

  // 10. 追蹤紀錄 (真實內容、客戶回饋、下一步)
  const followUps: FollowUp[] = [
    {
      id: 'fu_01',
      customerRegistrationId: 'reg_dn_02_expiring_eligible',
      storeId: 'store_daan_a',
      agentId: 'usr_agent_a',
      contactTime: offsetDate(-3, -2), // 3 天前，符合 14 天內有效追蹤規範！
      method: 'PHONE',
      summary: '去電與張董討論敦南峰景 A2-8F 棟別配置與付款條件。',
      customerResponse: '張董表示對 8F 採光非常滿意，但希望了解工期進度與自備款各期繳交比例，有意帶太太再次現場確認。',
      nextStep: '提供完整工程繳款明細表，並預約本週六下午帶張太太至案場看樣品屋。',
      nextFollowUpDate: offsetDate(3),
      recordedBy: '林業務',
      isEffectiveFollowUp: true,
      createdAt: offsetDate(-3, -2),
    },
    {
      id: 'fu_02',
      customerRegistrationId: 'reg_dn_01_a',
      storeId: 'store_daan_a',
      agentId: 'usr_agent_a',
      contactTime: offsetDate(-5),
      method: 'LINE',
      summary: '傳送 A1-12F 格局圖與周邊實價登錄行情。',
      customerResponse: '客戶已讀並回覆：「有收到，資料很清楚，目前跟家人在討論貸款成數。」',
      nextStep: '三天後主動追蹤家人討論意見，並提供配合銀行優惠房貸試算。',
      nextFollowUpDate: offsetDate(2),
      recordedBy: '林業務',
      isEffectiveFollowUp: true,
      createdAt: offsetDate(-5),
    },
    {
      id: 'fu_03_ineligible_old',
      customerRegistrationId: 'reg_dn_04_ineligible',
      storeId: 'store_xinyi_b',
      agentId: 'usr_agent_b',
      contactTime: offsetDate(-22), // 22 天前（已超出 14 天規範，不符合續期資格）
      method: 'PHONE',
      summary: '初步了解購屋需求。',
      customerResponse: '表示考慮中。',
      nextStep: '待客戶主動聯繫。',
      nextFollowUpDate: offsetDate(-10),
      recordedBy: '黃業務',
      isEffectiveFollowUp: false,
      createdAt: offsetDate(-22),
    },
    {
      id: 'fu_04',
      customerRegistrationId: 'reg_mv_05_pending_renewal',
      storeId: 'store_xinyi_b',
      agentId: 'usr_agent_b',
      contactTime: offsetDate(-2),
      method: 'ON_SITE',
      summary: '孫總經理伉儷親臨政大美墅現場會勘庭院與車位。',
      customerResponse: '對別墅內部自備電梯很滿意，長輩上下樓方便，希望爭取總價含冷氣空調補助。',
      nextStep: '向代銷中心回報議價意願，並提出保留續期申請以完成家族會議決定。',
      nextFollowUpDate: offsetDate(5),
      recordedBy: '黃業務',
      isEffectiveFollowUp: true,
      createdAt: offsetDate(-2),
    },
  ];

  // 11. 帶看紀錄 (包含已排程、已完成)
  const viewings: Viewing[] = [
    {
      id: 'vw_01',
      customerRegistrationId: 'reg_dn_02_expiring_eligible',
      projectId: 'proj_dunnan',
      unitId: 'unit_dn_a2_8f',
      scheduledTime: offsetDate(-6, 4), // 6 天前已完成帶看
      status: 'COMPLETED',
      receptionistName: '林業務（現場專案 李專案協同）',
      customerFeedback: '客戶對戶外視野與敦南林蔭景觀高度認可，評估主臥衛浴是否能微調客變。',
      objections: '擔心面敦化南路車流量與高樓層風切聲。',
      nextStep: '提供 YKK 氣密窗與 6+6 Low-E 玻璃原廠隔音檢測報告。',
      completedAt: offsetDate(-6, 6),
      createdAt: offsetDate(-8),
    },
    {
      id: 'vw_02_upcoming',
      customerRegistrationId: 'reg_dn_01_a',
      projectId: 'proj_dunnan',
      unitId: 'unit_dn_a1_12f',
      scheduledTime: offsetDate(2, 2), // 即將到來的帶看
      status: 'SCHEDULED',
      receptionistName: '林業務',
      customerFeedback: '',
      objections: '',
      nextStep: '準備工程圖樣本與周遭生活機能導覽地圖。',
      createdAt: offsetDate(-2),
    },
    {
      id: 'vw_03_completed_mori',
      customerRegistrationId: 'reg_mv_05_pending_renewal',
      projectId: 'proj_mori_villa',
      unitId: 'unit_mv_v2',
      scheduledTime: offsetDate(-4, 3),
      status: 'COMPLETED',
      receptionistName: '黃業務',
      customerFeedback: '孫總全家一同實地考察，特別喜愛後方獨立花園。',
      objections: '政大山區潮濕疑慮。',
      nextStep: '說明全棟大金全熱交換機與全室除濕系統標準配備。',
      completedAt: offsetDate(-4, 5),
      createdAt: offsetDate(-7),
    },
  ];

  // 12. 續期申請 (案例：B店黃業務申請中，待中心審核)
  const renewalRequests: RenewalRequest[] = [
    {
      id: 'ren_01_pending',
      customerRegistrationId: 'reg_mv_05_pending_renewal',
      storeId: 'store_xinyi_b',
      agentId: 'usr_agent_b',
      originalExpiryDate: offsetDate(2),
      requestedDays: 30,
      reason: '客戶孫總全家已於4天前完成現場帶看，目前正召集家族董事會議決議簽約預算，極具成交誠意，申請延長專屬保留期30天。',
      linkedRecordType: 'viewing',
      linkedRecordId: 'vw_03_completed_mori',
      status: 'PENDING', // 待審核
      createdAt: offsetDate(-1),
    },
  ];

  // 13. 交易紀錄 (涵蓋申報中、已簽約、已成交)
  const transactions: Transaction[] = [
    // 交易 1：下訂申報中 (門店提出，待中心確認)
    {
      id: 'tx_01_deposit_reported',
      customerRegistrationId: 'reg_dn_06_deposit_rep',
      projectId: 'proj_dunnan',
      unitId: 'unit_dn_a1_12f',
      storeId: 'store_daan_a',
      agentId: 'usr_agent_a',
      stage: 'DEPOSIT_REPORTED',
      dealPrice: 39800000,
      depositAmount: 1000000,
      transactionDate: offsetDate(-1),
      reportNote: '客戶高會計師已付訂金 100 萬元，申報下訂 A1-12F，請代銷中心覆核並同步戶別狀態。',
      commissionSnapshotId: 'snap_reg_06',
      totalCommission: 1194000, // 3980萬 * 3%
      centerCommission: 358200, // 30%
      storeCommission: 835800, // 70%
      isSettled: false, // 申報中為估算，未結算
      createdAt: offsetDate(-1),
      updatedAt: offsetDate(-1),
    },
    // 交易 2：已簽約 (中心已確認)
    {
      id: 'tx_02_signed_confirmed',
      customerRegistrationId: 'reg_dn_07_signed',
      projectId: 'proj_dunnan',
      unitId: 'unit_dn_a2_8f',
      storeId: 'store_daan_a',
      agentId: 'usr_store_mgr_a',
      stage: 'CONTRACT_CONFIRMED',
      dealPrice: 48800000,
      depositAmount: 5000000,
      transactionDate: offsetDate(-10),
      reportNote: '合約用印完畢，首期簽約款已入信託專戶。',
      centerConfirmNote: '代銷中心王主管已查驗買賣契約書與匯款單無誤，核准生效。',
      centerConfirmedAt: offsetDate(-9),
      centerConfirmedBy: '王中心',
      commissionSnapshotId: 'snap_reg_07',
      totalCommission: 1464000, // 4880萬 * 3%
      centerCommission: 439200, // 30%
      storeCommission: 1024800, // 70%
      isSettled: false,
      createdAt: offsetDate(-12),
      updatedAt: offsetDate(-9),
    },
    // 交易 3：已成交 (完整結算)
    {
      id: 'tx_03_deal_confirmed',
      customerRegistrationId: 'reg_mv_08_deal_closed',
      projectId: 'proj_mori_villa',
      unitId: 'unit_mv_v1',
      storeId: 'store_xinyi_b',
      agentId: 'usr_store_mgr_b',
      stage: 'DEAL_CONFIRMED',
      dealPrice: 53000000,
      depositAmount: 8000000,
      transactionDate: offsetDate(-20),
      reportNote: 'A1 棟尊榮別墅成交申報，總價 5,300 萬。',
      centerConfirmNote: '代銷中心確認交屋完成與建商佣金款入帳，正式核發分佣結算。',
      centerConfirmedAt: offsetDate(-5),
      centerConfirmedBy: '王中心',
      commissionSnapshotId: 'snap_reg_08',
      totalCommission: 800000, // 固定 80 萬
      centerCommission: 160000, // 20%
      storeCommission: 640000, // 80%
      isSettled: true, // 已正式結算
      createdAt: offsetDate(-20),
      updatedAt: offsetDate(-5),
    },
  ];

  // 14. 操作紀錄 (稽核日誌)
  const auditLogs: AuditLog[] = [
    {
      id: 'log_01',
      timestamp: offsetDate(-15),
      operatorId: 'usr_center_admin',
      operatorName: '王中心',
      role: 'center_admin',
      actionType: 'PUBLISH_COMMISSION',
      entityType: 'COMMISSION',
      entityId: 'comm_dunnan_v2',
      summary: '發布太平洋敦南峰景 V2.0 分佣辦法',
      beforeValue: 'V1.0 (3.0%, 中心 30% / 門店 70%)',
      afterValue: 'V2.0 (3.5%, 中心 25% / 門店 75%)',
      reason: '配合中秋強銷檔期激勵門店衝刺可售戶數',
    },
    {
      id: 'log_02',
      timestamp: offsetDate(-8),
      operatorId: 'usr_agent_a',
      operatorName: '林業務',
      role: 'agent',
      storeId: 'store_daan_a',
      storeName: '示範A店（大安旗艦店）',
      actionType: 'CREATE_CUSTOMER_REG',
      entityType: 'CUSTOMER_REG',
      entityId: 'reg_dn_01_a',
      summary: '登記客戶 李先生 於建案 太平洋敦南峰景，自動取得 30 天專屬保留期',
      beforeValue: '-',
      afterValue: '保留到期日: 30天後，分佣快照鎖定 V1.0 (3.0%)',
      reason: '網路預約客專屬洽談',
    },
    {
      id: 'log_03',
      timestamp: offsetDate(-2),
      operatorId: 'usr_agent_b',
      operatorName: '黃業務',
      role: 'agent',
      storeId: 'store_xinyi_b',
      storeName: '示範B店（信義加盟店）',
      actionType: 'CREATE_CUSTOMER_REG_CONFLICT',
      entityType: 'CUSTOMER_REG',
      entityId: 'reg_dn_01_b_conflict',
      summary: '登記客戶李先生於太平洋敦南峰景，偵測同案已存在保留中登記，轉入「歸屬待判定」',
      beforeValue: '-',
      afterValue: '狀態: CONFLICT_PENDING (待中心裁定)',
      reason: '重複電話識別碼 0912-345-678 於同建案衝突',
    },
    {
      id: 'log_04',
      timestamp: offsetDate(-1),
      operatorId: 'usr_agent_b',
      operatorName: '黃業務',
      role: 'agent',
      storeId: 'store_xinyi_b',
      storeName: '示範B店（信義加盟店）',
      actionType: 'APPLY_RENEWAL',
      entityType: 'RENEWAL',
      entityId: 'ren_01_pending',
      summary: '為客戶孫總經理申請森活美墅保留期延長 30 天',
      beforeValue: '原到期日: 剩餘 2 天',
      afterValue: '申請延長 30 天 (待審核)',
      reason: '已於4天前完成現場實地帶看，決策議決中',
    },
    {
      id: 'log_05',
      timestamp: offsetDate(-1),
      operatorId: 'usr_agent_a',
      operatorName: '林業務',
      role: 'agent',
      storeId: 'store_daan_a',
      storeName: '示範A店（大安旗艦店）',
      actionType: 'REPORT_TRANSACTION',
      entityType: 'TRANSACTION',
      entityId: 'tx_01_deposit_reported',
      summary: '提出敦南峰景 A1-12F 下訂申報 (金額 3,980 萬元)',
      beforeValue: '戶別狀態: 可售',
      afterValue: '交易狀態: DEPOSIT_REPORTED (待中心確認)',
      reason: '收受小訂 100 萬元',
    },
    {
      id: 'log_06',
      timestamp: offsetDate(-9),
      operatorId: 'usr_center_admin',
      operatorName: '王中心',
      role: 'center_admin',
      actionType: 'CONFIRM_TRANSACTION',
      entityType: 'TRANSACTION',
      entityId: 'tx_02_signed_confirmed',
      summary: '代銷中心確認敦南峰景 A2-8F 簽約申報生效，同步戶別狀態為「已簽約」',
      beforeValue: '戶別狀態: 已下訂',
      afterValue: '戶別狀態: 已簽約 (SIGNED)',
      reason: '核對信託專戶首期款 500 萬元入帳無誤',
    },
  ];

  return {
    users,
    stores,
    projects,
    units,
    projectAssignments,
    customers,
    customerRegistrations,
    commissionVersions,
    commissionSnapshots,
    followUps,
    renewalRequests,
    viewings,
    transactions,
    auditLogs,
  };
}
